# Generated by Django 5.2.10 on 2026-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fayda_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tin_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
