# Generated by Django 5.2.10 on 2026-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maidprofile_city_maidprofile_region_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='primary_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maidprofile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
