# Generated by Django 5.2.10 on 2026-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maidprofile_primary_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='contract_preference',
            field=models.CharField(blank=True, choices=[('live_in', 'Live-in'), ('live_out', 'Live-out'), ('both', 'Both')], max_length=50, null=True),
        ),
    ]
