# Generated by Django 5.2.10 on 2026-04-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_maidprofile_contract_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidprofile',
            name='contract_preference',
        ),
    ]
